export interface GitHubFile {
  path: string;
  content: string;
}

interface RepoResponse {
  html_url: string;
  full_name: string;
  name: string;
  default_branch: string;
}

interface GitHubUserResponse {
  login: string;
}

interface RefResponse {
  object: { sha: string };
}

interface CommitResponse {
  tree: { sha: string };
  sha: string;
}

interface BlobResponse {
  sha: string;
}

interface TreeResponse {
  sha: string;
}

interface NewCommitResponse {
  sha: string;
}

export async function getUser(accessToken: string): Promise<GitHubUserResponse> {
  const res = await fetch("https://api.github.com/user", {
    headers: {
      Authorization: `Bearer ${accessToken}`,
      Accept: "application/vnd.github.v3+json",
    },
  });
  if (!res.ok) throw new Error(`GitHub user fetch failed: ${res.status}`);
  return res.json() as Promise<GitHubUserResponse>;
}

export async function createRepo(
  accessToken: string,
  repoName: string,
  description: string
): Promise<RepoResponse> {
  const res = await fetch("https://api.github.com/user/repos", {
    method: "POST",
    headers: {
      Authorization: `Bearer ${accessToken}`,
      Accept: "application/vnd.github.v3+json",
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      name: repoName,
      description,
      private: false,
      auto_init: true,
    }),
  });
  if (!res.ok) {
    const err = await res.json() as { message?: string };
    throw new Error(`GitHub repo creation failed: ${err.message ?? res.status}`);
  }
  return res.json() as Promise<RepoResponse>;
}

export async function pushFile(
  accessToken: string,
  owner: string,
  repo: string,
  path: string,
  content: string,
  message: string
): Promise<void> {
  const encoded = Buffer.from(content).toString("base64");
  const res = await fetch(
    `https://api.github.com/repos/${owner}/${repo}/contents/${path}`,
    {
      method: "PUT",
      headers: {
        Authorization: `Bearer ${accessToken}`,
        Accept: "application/vnd.github.v3+json",
        "Content-Type": "application/json",
      },
      body: JSON.stringify({ message, content: encoded }),
    }
  );
  if (!res.ok) throw new Error(`GitHub file push failed: ${res.status}`);
}

export async function pushMultipleFiles(
  accessToken: string,
  owner: string,
  repo: string,
  files: GitHubFile[]
): Promise<void> {
  const headers = {
    Authorization: `Bearer ${accessToken}`,
    Accept: "application/vnd.github.v3+json",
    "Content-Type": "application/json",
  };

  // Get default branch + latest commit SHA
  const repoRes = await fetch(`https://api.github.com/repos/${owner}/${repo}`, { headers });
  const repoData = await repoRes.json() as RepoResponse;
  const branch = repoData.default_branch ?? "main";

  const refRes = await fetch(
    `https://api.github.com/repos/${owner}/${repo}/git/refs/heads/${branch}`,
    { headers }
  );
  const refData = await refRes.json() as RefResponse;
  const latestCommitSha = refData.object.sha;

  // Get base tree SHA
  const commitRes = await fetch(
    `https://api.github.com/repos/${owner}/${repo}/git/commits/${latestCommitSha}`,
    { headers }
  );
  const commitData = await commitRes.json() as CommitResponse;
  const baseTreeSha = commitData.tree.sha;

  // Create blobs in parallel
  const treeItems = await Promise.all(
    files.map(async (file) => {
      const blobRes = await fetch(
        `https://api.github.com/repos/${owner}/${repo}/git/blobs`,
        {
          method: "POST",
          headers,
          body: JSON.stringify({ content: file.content, encoding: "utf-8" }),
        }
      );
      const blob = await blobRes.json() as BlobResponse;
      return {
        path: file.path,
        mode: "100644" as const,
        type: "blob" as const,
        sha: blob.sha,
      };
    })
  );

  // Create tree
  const treeRes = await fetch(
    `https://api.github.com/repos/${owner}/${repo}/git/trees`,
    {
      method: "POST",
      headers,
      body: JSON.stringify({ base_tree: baseTreeSha, tree: treeItems }),
    }
  );
  const treeData = await treeRes.json() as TreeResponse;

  // Create commit
  const newCommitRes = await fetch(
    `https://api.github.com/repos/${owner}/${repo}/git/commits`,
    {
      method: "POST",
      headers,
      body: JSON.stringify({
        message: "feat: initial codebase generated by Qrew",
        tree: treeData.sha,
        parents: [latestCommitSha],
      }),
    }
  );
  const newCommit = await newCommitRes.json() as NewCommitResponse;

  // Update branch ref
  await fetch(
    `https://api.github.com/repos/${owner}/${repo}/git/refs/heads/${branch}`,
    {
      method: "PATCH",
      headers,
      body: JSON.stringify({ sha: newCommit.sha }),
    }
  );
}
