import { type NextRequest, NextResponse } from "next/server";
import { createClient } from "@/lib/supabase-server";

interface PushRequestBody {
  startupId: string;
  repoName: string;
  files: Array<{ path: string; content: string }>;
}

interface GitHubRepoResponse {
  id: number;
  name: string;
  html_url: string;
  default_branch: string;
}

interface GitHubRefResponse {
  object: { sha: string };
}

interface GitHubBlobResponse {
  sha: string;
}

interface GitHubTreeResponse {
  sha: string;
}

interface GitHubCommitResponse {
  sha: string;
}

async function githubFetch(
  path: string,
  token: string,
  options: RequestInit = {}
): Promise<Response> {
  return fetch(`https://api.github.com${path}`, {
    ...options,
    headers: {
      Authorization: `Bearer ${token}`,
      Accept: "application/vnd.github+json",
      "X-GitHub-Api-Version": "2022-11-28",
      "Content-Type": "application/json",
      ...(options.headers ?? {}),
    },
  });
}

export async function POST(req: NextRequest) {
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

  const body = (await req.json()) as PushRequestBody;
  const { startupId, repoName, files } = body;

  if (!files?.length) return NextResponse.json({ error: "No files provided" }, { status: 400 });

  // Get GitHub token + username from profiles
  const { data: profile } = await supabase
    .from("profiles")
    .select("github_access_token, github_username")
    .eq("id", user.id)
    .single();

  const token = (profile as { github_access_token?: string } | null)?.github_access_token;
  const username = (profile as { github_username?: string } | null)?.github_username;

  if (!token || !username) {
    return NextResponse.json({ error: "GitHub not connected. Connect GitHub first." }, { status: 400 });
  }

  const safeName = repoName
    .toLowerCase()
    .replace(/[^a-z0-9-]/g, "-")
    .replace(/-+/g, "-")
    .replace(/^-|-$/g, "")
    .slice(0, 100);

  try {
    // ── 1. Create repo (or get existing) ─────────────────────────────────────
    let repo: GitHubRepoResponse;

    const getRes = await githubFetch(`/repos/${username}/${safeName}`, token);
    if (getRes.ok) {
      repo = (await getRes.json()) as GitHubRepoResponse;
    } else {
      const createRes = await githubFetch("/user/repos", token, {
        method: "POST",
        body: JSON.stringify({
          name: safeName,
          private: false,
          auto_init: true,
          description: `Generated by Qrew AI Founder OS`,
        }),
      });
      if (!createRes.ok) {
        const err = await createRes.text();
        throw new Error(`Failed to create repo: ${err.slice(0, 200)}`);
      }
      repo = (await createRes.json()) as GitHubRepoResponse;
      // Wait for GitHub to initialize the repo
      await new Promise(r => setTimeout(r, 2000));
    }

    const branch = repo.default_branch ?? "main";

    // ── 2. Get current HEAD SHA ───────────────────────────────────────────────
    const refRes = await githubFetch(`/repos/${username}/${safeName}/git/refs/heads/${branch}`, token);
    if (!refRes.ok) throw new Error(`Failed to get HEAD ref: ${refRes.status}`);
    const refData = (await refRes.json()) as GitHubRefResponse;
    const baseSha = refData.object.sha;

    // ── 3. Create blobs for each file ─────────────────────────────────────────
    const blobShas = await Promise.all(
      files.map(async (file) => {
        const blobRes = await githubFetch(`/repos/${username}/${safeName}/git/blobs`, token, {
          method: "POST",
          body: JSON.stringify({
            content: Buffer.from(file.content).toString("base64"),
            encoding: "base64",
          }),
        });
        if (!blobRes.ok) throw new Error(`Blob creation failed for ${file.path}`);
        const blob = (await blobRes.json()) as GitHubBlobResponse;
        return { path: file.path, sha: blob.sha };
      })
    );

    // ── 4. Create tree ────────────────────────────────────────────────────────
    const treeRes = await githubFetch(`/repos/${username}/${safeName}/git/trees`, token, {
      method: "POST",
      body: JSON.stringify({
        base_tree: baseSha,
        tree: blobShas.map(({ path, sha }) => ({
          path,
          mode: "100644",
          type: "blob",
          sha,
        })),
      }),
    });
    if (!treeRes.ok) throw new Error(`Tree creation failed: ${treeRes.status}`);
    const tree = (await treeRes.json()) as GitHubTreeResponse;

    // ── 5. Create commit ──────────────────────────────────────────────────────
    const commitRes = await githubFetch(`/repos/${username}/${safeName}/git/commits`, token, {
      method: "POST",
      body: JSON.stringify({
        message: "🚀 Initial commit — generated by Qrew AI Founder OS",
        tree: tree.sha,
        parents: [baseSha],
      }),
    });
    if (!commitRes.ok) throw new Error(`Commit creation failed: ${commitRes.status}`);
    const commit = (await commitRes.json()) as GitHubCommitResponse;

    // ── 6. Update branch reference ────────────────────────────────────────────
    const updateRes = await githubFetch(
      `/repos/${username}/${safeName}/git/refs/heads/${branch}`,
      token,
      {
        method: "PATCH",
        body: JSON.stringify({ sha: commit.sha, force: false }),
      }
    );
    if (!updateRes.ok) throw new Error(`Ref update failed: ${updateRes.status}`);

    const repoUrl = repo.html_url;

    // Save to startups + company_brain
    await Promise.all([
      supabase.from("startups").update({ github_url: repoUrl }).eq("id", startupId),
      supabase.from("company_brain").update({ github_url: repoUrl, updated_at: new Date().toISOString() }).eq("startup_id", startupId),
    ]);

    return NextResponse.json({ repoUrl, repoName: safeName });
  } catch (err) {
    const msg = err instanceof Error ? err.message : "GitHub push failed";
    console.error("[github/push]", msg);
    return NextResponse.json({ error: msg }, { status: 500 });
  }
}
